### ISSUE TITLE
diff_inv is not using xi parameter

### ISSUE THREAD

**Issue by knixon2** [alkaline-ml/pmdarima#410]
**Describe the bug**
Regardless of what value I put into the diff_inv function for xi, it returns the same array.  The array it returns is correct, except it doesn't adjust by the xi.

**To Reproduce**  
I was trying to difference an array, then inverse difference it to check and make sure I got the original array and thus understood how to use the function.  The docs don't specify exactly how to use xi, so the issue may be that I'm not doing that correctly.

```python
diff(c( 5, 3, 6, 2, 10), 1, 1) #difference this array once, returns:  array([-2.,  3., -4.,  8.])

diff_inv(c( -2, 3, -4,  8), 1, 1, xi=[5]) #inverse the differencing, returns: array([ 0., -2.,  1., -3.,  5.])
```

**Versions**

System:
    python: 3.7.0 (default, Jun 28 2018, 07:39:16)  [Clang 4.0.1 (tags/RELEASE_401/final)]
executable: /opt/anaconda3/envs/CDCtest/bin/python
   machine: Darwin-19.6.0-x86_64-i386-64bit
Python dependencies:
        pip: 20.3.3
 setuptools: 51.1.1
    sklearn: 0.23.2
statsmodels: 0.12.1
      numpy: 1.19.4
      scipy: 1.5.1
     Cython: 0.29.17
     pandas: 1.1.5
     joblib: 1.0.0
   pmdarima: 1.8.0

**Expected behavior/Actual behavior**
I would expect the diff_inv to return the original array (5, 3, 6, 2, 10).  If you add xi, 5, to all the values in the array diff_inv returns, then it does return the original array.  So it seems the issue is just with the xi parameter.  This would be a quick fix for me to just add it for one level of differencing, but for my application I need to inverse two levels of differencing, and I'm not sure how to correct that manually.

**Comment by tgsmith61591** [comment]
Thank you for pointing this out. We will have this fixed in the next release.

**Comment by Rexpert** [comment]
This issue still persists in v1.8.5. 

As a quick fix, I suggest:
```Python
from pmdarima.utils import c, diff_inv
from itertools import cycle
from numpy import fromiter

x_diff = c(-2, 3, -4,  8)
xi     = [5]
diff_inv(x_diff, 1,1) + fromiter(cycle(xi), count=len(x_diff)+len(xi), dtype=float)
```
```Python
> array([ 5.,  3.,  6.,  2., 10.])
```
